# Generated by Django 4.1.3 on 2022-11-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('image_array', models.JSONField()),
                ('symbol', models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('н', 'н')], max_length=1, verbose_name='Символ')),
            ],
            options={
                'verbose_name': 'Изображение ячейки (сырые данные)',
                'verbose_name_plural': 'Изображения ячеек (сырые данные)',
            },
        ),
    ]
